"""empty message

Revision ID: 5ab14f67fd3b
Revises: 
Create Date: 2025-09-30 10:07:12.989315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab14f67fd3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FriendResult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FriendResult', schema=None) as batch_op:
        batch_op.drop_column('invite_code')

    # ### end Alembic commands ###
