"""empty message

Revision ID: 8385e6fe2575
Revises: 
Create Date: 2025-10-09 17:16:54.856662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8385e6fe2575'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FriendResult', schema=None) as batch_op:
        batch_op.alter_column('read',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FriendResult', schema=None) as batch_op:
        batch_op.alter_column('read',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###
